# -*- coding: utf-8 -*-
"""p106

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x4RYF8hPfHjFkjzOfPW5Uib3fTjYBsVw
"""

from google.colab import files
data_to_load=files.upload()

import plotly.express as px
import csv
import numpy as np
def plotfigure(data_path):
  with open ("p106.csv")as csv_file:
    df=csv.DictReader(csv_file)
    fig=px.scatter(df,x="Days Present",y="Marks In Percentage") 
    fig.show()

def getdatasource(data_path):
  marks_in_percentage=[]
  days_present=[]
  with open (data_path)as csv_file:
    csv_reader=csv.DictReader(csv_file)
    for row in csv_reader:
       marks_in_percentage.append(float(row["Marks In Percentage"]))
       days_present.append(float(row["Days Present"]))
  return{"x": marks_in_percentage,"y":days_present}

def findcorelation(datasource):
  corelation=np.corrcoef(datasource["x"],datasource["y"])
  print("corelation between Marks In Percentage vs Days Present ",corelation[0,1])

data_path="p106.csv"
datasource=getdatasource(data_path)
findcorelation(datasource)
plotfigure(data_path)

from google.colab import files
data_to_load=files.upload()

import plotly.express as px
import csv
with open ("coffee.csv")as csv_file:
  df=csv.DictReader(csv_file)
  fig=px.scatter(df,x="Coffee in ml",y="sleep in hours",color="week") 
  fig.show()